### ISSUE TITLE
Slack link expired

### ISSUE THREAD

**Issue by MParvin** [collabnix/terraform#28]
Please change the Slack link.
Thanks
![image](https://user-images.githubusercontent.com/7812338/107117422-7b1c5b00-688f-11eb-9484-cffed6b41621.png)

**Comment by ajeetraina** [comment]
Fixed.

**Comment by MParvin** [comment]
@ajeetraina  thank you
the slack link in the readme file is so

**Comment by collabnix** [comment]
Fixed.
